MODEL:
  BACKBONE: 'darknet53'
  ANCHOR_SIZES: [32, 64, 128, 256, 512]
  ANCHOR_STRIDES: [8, 16, 32, 64, 128]
DATASETS:
  TRAIN: './data/Repere_1.0/train.txt'
  VALID: './data/Repere_1.0/validation.txt'
  TEST: './data/Repere_1.0/testing.txt'
  MESH_DIR: './data/Repere_1.0/models/'
  BBOX_FILE: './data/Repere_1.0/repere_bbox.json'
  MESH_DIAMETERS: [64.98]
  N_CLASS: 2
INPUT:
  INTERNAL_WIDTH: 480
  INTERNAL_HEIGHT: 270
  INTERNAL_K: [260.359268188476, 0, 235.2060635193502, 0, 258.9642364501953, 132.706312109753, 0, 0, 1]
SOLVER:
  IMS_PER_BATCH: 8
  # 
  BASE_LR: 0.01
  STEPS_PER_EPOCH: 10000
  MAX_ITER: 100000
  SCHEDULER_POLICY: 'multi_steps'
  SCHEDULER_PARAMS: {'steps': [50000, 70000], 'gamma': 0.1}
  # 
  LOSS_WEIGHT_CLS: 0.01
  LOSS_WEIGHT_REG: 0.1
  POSITIVE_LAMBDA: 1.0
  AUGMENTATION_SHIFT: 0.1
  AUGMENTATION_SCALE: 0.1
  AUGMENTATION_ROTATION: 180
TEST:
  IMS_PER_BATCH: 1
  CONFIDENCE_TH: 0.3
